[package]
name = "parallel-hamt-cache-conscious"
version = "0.1.0"
authors = ["chichunchen <chichunchen844@gmail.com>", "Wang, Shaojie <swang115@ur.rochester.edu>"]

[dependencies]
rand="0.4.2"
chashmap="2.2.0"
rayon="1.0.1"

[lib]
name = "cchamt"
path = "src/lib.rs"
